# Scratch Pad

Scratch pad for all the work in Assignment 2

In [1]:
import numpy as np
from A2Part1 import genSine
from A2Part2 import genComplexSine
from A2Part3 import DFT
from A2Part4 import IDFT
from A2Part5 import genMagSpec

## A1

In [2]:
a = 1.0
f = 10.0
t = 0.1
phi = 1.0
fs = 50.0
big_t = 1/fs
t = 0.1
#A=1.0, f = 10.0, phi = 1.0, fs = 50.0 and t = 0.1, the output numpy 

In [3]:
a*np.cos((2*np.pi*f*big_t)+phi)

-0.633323868761624

In [4]:
length = t*fs
x = [a*np.cos((2*np.pi*f*big_t*n)+phi) for n in range(int(length))]
x

[0.5403023058681398,
 -0.633323868761624,
 -0.9317179826494012,
 0.05749048755480921,
 0.9672490579880761]

In [5]:
a1_x = genSine(a,f, phi, fs, t)

In [6]:
a1_x == x

True

## A2

In [7]:
k = 1
N = 5

In [8]:
a = 1
omega = (2*np.pi*k)
big_t = 1/N
phi = 0
real_x = [a*np.cos((omega*big_t*n)+phi) for n in range(int(N))]
real_x

[1.0,
 0.30901699437494745,
 -0.8090169943749473,
 -0.8090169943749476,
 0.30901699437494723]

In [9]:
imaginary_x = ([-1j*a*np.sin((omega*big_t*n)+phi) for n in range(int(N))])
imaginary_x

[0j,
 -0.9510565162951535j,
 -0.5877852522924732j,
 0.587785252292473j,
 0.9510565162951536j]

In [10]:
complex_x = (np.add(real_x,imaginary_x))
complex_x

array([ 1.        +0.j        ,  0.30901699-0.95105652j,
       -0.80901699-0.58778525j, -0.80901699+0.58778525j,
        0.30901699+0.95105652j])

In [11]:
a2_complex_x = genComplexSine(k,N)

In [12]:
a2_complex_x == complex_x

array([ True,  True,  True,  True,  True])

## A3

In [13]:
a3_x = [1,2,3,4]

In [14]:
N= len(a3_x)*1.0
dft_x = []
for k in range(int(N)):
    exp_k = []
    for n in range(int(N)):
        exp_k.append(-1j*2*np.pi*k*n/N)
    eulers_v = np.exp(exp_k)
    dft_x.append(sum(a3_x*eulers_v))
dft_rs = np.array(dft_x)

In [15]:
a3_rs = DFT(np.array(a3_x))

In [16]:
a3_rs == dft_rs

array([ True,  True,  True,  True])

In [17]:
a3_rs

array([10.+0.00000000e+00j, -2.+2.00000000e+00j, -2.-9.79717439e-16j,
       -2.-2.00000000e+00j])

In [18]:
np.abs(a3_rs)

array([10.        ,  2.82842712,  2.        ,  2.82842712])

## A4

In [19]:
a4_x = np.array([1,1,1,1])

In [20]:
N = len(a4_x)*1.0
idft_x = []
for k in range(int(N)):
    exp_k = []
    for n in range(int(N)):
        exp_k.append(1j*2*np.pi*k*n/N)
    eulers_v = np.exp(exp_k)
    idft_x.append((sum((a4_x)*eulers_v))/N)
idft_rs = np.array(idft_x)

In [21]:
idft_rs

array([ 1.00000000e+00+0.00000000e+00j, -4.59242550e-17+5.55111512e-17j,
        0.00000000e+00+6.12323400e-17j,  8.22616137e-17+8.32667268e-17j])

In [22]:
idft_a4 = IDFT(a4_x)

In [23]:
idft_a4==idft_rs

array([ True,  True,  True,  True])

## Testing on DFT + IDFT

In [24]:
a3_x

[1, 2, 3, 4]

In [25]:
IDFT(DFT(a3_x))

array([1.-5.55111512e-16j, 2.-2.77555756e-16j, 3.-1.11022302e-16j,
       4.+2.77555756e-16j])

## A5

In [26]:
genMagSpec(a3_x)

array([10.        ,  2.82842712,  2.        ,  2.82842712])